const mongoose=require("mongoose");
const schema=mongoose.Schema;

const bookingSchema=new schema({
    listing:{
        type:schema.Types.ObjectId,
        ref:"Listing",
        required:true,
    },
    user:{
        type:schema.Types.ObjectId,
        ref:"User",
        required:true,
    },
    checkIn:{
        type:Date,
        required:true,
    },
    checkOut:{
        type:Date,
        required:true,
    },
    guests:{
        type:Number,
        required:true,
        min:1,
    },
    nights:{
        type:Number,
        required:true,
        min:1,
    },
    totalPrice:{
        type:Number,
        required:true,
        min:0,
    },
    paymentMode:{
        type:String,
        enum:["full","deposit"],
        default:"full",
    },
    depositAmount:{
        type:Number,
        default:0,
        min:0,
    },
    locked:{
        type:Boolean,
        default:false,
    },
    lockedPrice:{
        type:Number,
        default:null,
        min:0,
    },
    status:{
        type:String,
        enum:["confirmed","cancelled"],
        default:"confirmed",
    },
    createdAt:{
        type:Date,
        default:Date.now,
    },
});

module.exports=mongoose.model("Booking",bookingSchema);